[package]
name = "boilerplate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_of_code_lib = { path = "../advent_of_code_lib/" }
itertools = "0.10.5"
